POST http://localhost:8080/v1/story
Content-Type: application/json

{
  "id": "AEEtvd4",
  "title": "Standard Go Project Layout",
  "author": "GoLang",
  "votes": 12,
  "url": "https://github.com/golang-standards/project-layout"
}

###

GET http://localhost:8080/v1/story?page=1&limit=2
