version: '3.3'

services:
  database:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./migration/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: gokit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_DB_USER: "postgres"
      APP_DB_PASSWORD: "postgres"
      APP_DB_HOST: "database"
      APP_DB_DATABASE: "app"
    depends_on:
      - database

